# Logistic Regression

In [48]:
%matplotlib inline

import numpy as np
import os
import string
import re
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [141]:
base_path = "/home/orsdanilo/Documents/ml_from_scratch/"
raw_fname = "data/raw/copen.dat"
#proc_fname = "data/processed/copen.raw"
proc_fname = "data/raw/candy-data.csv"
path_to_raw = os.path.join(base_path, raw_fname)
path_to_proc = os.path.join(base_path, proc_fname)

In [145]:
n_rows = 86
n_cols = 12

In [147]:
# data = np.loadtxt(path_to_proc, usecols=list(range(1, n_cols)), unpack=False)
data = np.genfromtxt(path_to_proc, delimiter=',', usecols=(range(1,n_cols+1)), skip_header=True)

data[:10,:]

array([[1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 7.3199999e-01, 8.6000001e-01, 6.6971725e+01],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        0.0000000e+00, 6.0399997e-01, 5.1099998e-01, 6.7602936e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.1000000e-02, 1.1600000e-01, 3.2261086e+01],
       [0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.1000000e-02, 5.1099998e-01, 4.6116505e+01],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 9.0600002e-01, 5.1099

In [54]:
y = d[:,2].reshape(-1,1)
y = np.where(y==1, 0, 1)
y[:10,:]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1]])

In [55]:
x = np.delete(d, 2, axis=1)
x[:10,:]

array([[ 1.,  1.,  1., 21.],
       [ 1.,  1.,  2., 21.],
       [ 1.,  1.,  3., 28.],
       [ 1.,  1.,  1., 14.],
       [ 1.,  1.,  2., 19.],
       [ 1.,  1.,  3., 37.],
       [ 1.,  2.,  1., 34.],
       [ 1.,  2.,  2., 22.],
       [ 1.,  2.,  3., 36.],
       [ 1.,  2.,  1., 17.]])

In [56]:
def normalized(a, axis=-1, order=2):
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)

In [88]:
x[:,-1] = normalized(x[:,-1])
x[:10,:]

array([[1.        , 1.        , 1.        , 0.08474565],
       [1.        , 1.        , 2.        , 0.08474565],
       [1.        , 1.        , 3.        , 0.1129942 ],
       [1.        , 1.        , 1.        , 0.0564971 ],
       [1.        , 1.        , 2.        , 0.07667464],
       [1.        , 1.        , 3.        , 0.14931377],
       [1.        , 2.        , 1.        , 0.13720725],
       [1.        , 2.        , 2.        , 0.08878116],
       [1.        , 2.        , 3.        , 0.14527826],
       [1.        , 2.        , 1.        , 0.06860362]])

In [135]:
alpha = 0.7
#w = np.random.rand(x.shape[1],1)
w = np.ones(x.shape[1]).reshape(-1,1)
w

array([[1.],
       [1.],
       [1.],
       [1.]])

In [136]:
x_train = x[:50]
x_test = x[50:]
y_train = y[:50]
y_test = y[50:]

m = x.shape[0]

In [91]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [137]:
for _ in range(8000):
    D = y - sigmoid(np.dot(x, w))
    w = w + (alpha/m)*np.dot(x.T, D)
    
    G = sigmoid(np.dot(x, w))
    #J = (1/m)*(np.dot(np.log(G).T,y)+np.dot(np.log(np.ones(G.shape)-G).T, np.ones(y.shape)-y))

In [138]:
w

array([[-0.31227604],
       [-0.29232944],
       [-0.54458512],
       [ 8.72065326]])

In [139]:
G = sigmoid(np.dot(x_test, w))
y_pred = np.where(G>0.5, 1, 0)
y_pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [140]:
y_test

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])