# Logistic Regression

In [48]:
%matplotlib inline

import numpy as np
import os
import string
import re
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [49]:
base_path = "/home/orsdanilo/Documents/ml_from_scratch/"
raw_fname = "data/raw/copen.dat"
proc_fname = "data/processed/copen.raw"
path_to_raw = os.path.join(base_path, raw_fname)
path_to_proc = os.path.join(base_path, proc_fname)

In [50]:
n_rows = 72
n_cols = 6

In [51]:
data = np.loadtxt(path_to_proc, usecols=list(range(1, n_cols)), unpack=False)
data[:10,:]

array([[ 1.,  1.,  1.,  1., 21.],
       [ 1.,  1.,  1.,  2., 21.],
       [ 1.,  1.,  1.,  3., 28.],
       [ 1.,  1.,  2.,  1., 14.],
       [ 1.,  1.,  2.,  2., 19.],
       [ 1.,  1.,  2.,  3., 37.],
       [ 1.,  2.,  1.,  1., 34.],
       [ 1.,  2.,  1.,  2., 22.],
       [ 1.,  2.,  1.,  3., 36.],
       [ 1.,  2.,  2.,  1., 17.]])

In [54]:
y = d[:,2].reshape(-1,1)
y = np.where(y==1, 0, 1)
y[:10,:]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1]])

In [55]:
x = np.delete(d, 2, axis=1)
x[:10,:]

array([[ 1.,  1.,  1., 21.],
       [ 1.,  1.,  2., 21.],
       [ 1.,  1.,  3., 28.],
       [ 1.,  1.,  1., 14.],
       [ 1.,  1.,  2., 19.],
       [ 1.,  1.,  3., 37.],
       [ 1.,  2.,  1., 34.],
       [ 1.,  2.,  2., 22.],
       [ 1.,  2.,  3., 36.],
       [ 1.,  2.,  1., 17.]])

In [56]:
def normalized(a, axis=-1, order=2):
    l2 = np.atleast_1d(np.linalg.norm(a, order, axis))
    l2[l2==0] = 1
    return a / np.expand_dims(l2, axis)

In [88]:
x[:,-1] = normalized(x[:,-1])
x[:10,:]

array([[1.        , 1.        , 1.        , 0.08474565],
       [1.        , 1.        , 2.        , 0.08474565],
       [1.        , 1.        , 3.        , 0.1129942 ],
       [1.        , 1.        , 1.        , 0.0564971 ],
       [1.        , 1.        , 2.        , 0.07667464],
       [1.        , 1.        , 3.        , 0.14931377],
       [1.        , 2.        , 1.        , 0.13720725],
       [1.        , 2.        , 2.        , 0.08878116],
       [1.        , 2.        , 3.        , 0.14527826],
       [1.        , 2.        , 1.        , 0.06860362]])

In [135]:
alpha = 0.7
#w = np.random.rand(x.shape[1],1)
w = np.ones(x.shape[1]).reshape(-1,1)
w

array([[1.],
       [1.],
       [1.],
       [1.]])

In [136]:
x_train = x[:50]
x_test = x[50:]
y_train = y[:50]
y_test = y[50:]

m = x.shape[0]

In [91]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [137]:
for _ in range(8000):
    D = y - sigmoid(np.dot(x, w))
    w = w + (alpha/m)*np.dot(x.T, D)
    
    G = sigmoid(np.dot(x, w))
    #J = (1/m)*(np.dot(np.log(G).T,y)+np.dot(np.log(np.ones(G.shape)-G).T, np.ones(y.shape)-y))

In [138]:
w

array([[-0.31227604],
       [-0.29232944],
       [-0.54458512],
       [ 8.72065326]])

In [139]:
G = sigmoid(np.dot(x_test, w))
y_pred = np.where(G>0.5, 1, 0)
y_pred

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [140]:
y_test

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1]])